### ISSUE TITLE
Always False on Phonegap

### ISSUE THREAD

**Issue by martinlyder** [mariusbackes/cordova-plugin-theme-detection#3]
Hi 
Testing on iPhone iOS 13.1.3. With Darkmode enabled. But the plugin return false... I read somewhere that Phonegap Webview couldn't detect darkmode for CSS, but thought a plugin would retrieve the information native...

**Comment by mariusbackes** [comment]
I'm not familiar with PhoneGap. You are right, the plugin retrieves the information from the native side.
With the current browser engines you can also check activated mode with CSS:

`@media (prefers-color-scheme: dark) {
  .night { background: black; color:  #ddd; }
}`

With the CSS option it is detected with WebView.

If let me know more about your project, I might help you.

**Comment by martinlyder** [comment]
Hi thanks for the reply,

Adobe PhoneGap framework is an open source distribution of Apache Cordova...

And in Cordova I have the same challenges as in this thread : https://github.com/apache/cordova-ios/issues/629 it dont work in the compiled app, but works in the browser, thats why i found your plugin :) But can't get it to work..

Here is my code:
`    cordova.plugins.ThemeDetection.isDarkModeEnabled(`
`      function(success) {`
`        console.log(success.message);`
`            if (success.value) {`
`                 // dark mode - ThemeDetectionResponse`
`                    $('#cssthemecomp').attr('href','css/onsen-css-components.min.css');`
`                    $('#csstheme').attr('href','css/theme.css');`
`            }`
`      },`
`      function(error) {`
`        console.log(error);`
`      }`
`    );`

**Comment by mariusbackes** [comment]
Are you just building an iOS application? Or are you building an Android version, too?

Which Xcode do you use to build the app? And which iOS version does run on the native device?

**Comment by martinlyder** [comment]
Xcode 11.2.1 and iOS 13.1.3
Cordova 9.0.0 (cordova-lib@9.0.1)
Im building iOS first and then i make the Android project.

**Comment by mariusbackes** [comment]
Your function call looks correct and I tought you can use the CSS `prefers-color-scheme: dark` since iOS 13 in Safari. The WebView should recognize it.
Is the `cordova.plugins.ThemeDetection.isAvailable()` method also returning false?

What's the version of cordova-ios in your project? Cordova at version 9.0.0 seems the be the cli version.
The current cordova-ios version is 5.1.1

**Comment by martinlyder** [comment]
Ahh that could be the problem the iOS platform is 4.5.5

>  browser 5.0.4
>   ios 4.5.5

isAvailable() returns: `{value: true, message: "Dark mode detection is available"}`

**Comment by mariusbackes** [comment]
Does it fix your problem if you update the cordova-ios property?

**Comment by martinlyder** [comment]
Nope.. Still false... But I think its a Phonegap issue, the status bar is white with white text and switching to dark or light in Xcode dont change anything.

**Comment by angelofan** [comment]
@mariusbackes @martinlyder I encountered the same problem, here is some of my information
```
"cordova-plugin-theme-detection": "^1.2.0",
"cordova-ios": "^5.1.1",
```

![image](https://user-images.githubusercontent.com/20255750/70119547-75345400-16a5-11ea-9ac8-9605da6e522f.png)


Dark mode is enabled on my device, but the value of whether to enable dark mode is obtained in 2 ways, and all return false

**Comment by angelofan** [comment]
I not only need to enable the dark mode theme, but also need to change the color of the status bar according to the dark mode, so I need to access the dark mode through the js method. The css way cannot Help me solve all problems

**Comment by mariusbackes** [comment]
@angelofan Are you also using phonegap?

**Comment by angelofan** [comment]
@mariusbackes ionic3 with cordova

**Comment by mariusbackes** [comment]
I'm sorry, but I cannot reproduce this error.
I have started two new project. One Ionic project and one blank cordova project.

I'm running iOS 13.1 on my device.
I'm using the following dependencies:

```
"cordova-plugin-theme-detection": "^1.2.0",
"cordova-ios": "^5.1.1",
```

And for me the plugin is returning true, if dark mode is enabled

**Comment by angelofan** [comment]
@mariusbackes I plan to create an ionic3 project repository that only contains this plugin to reproduce this problem for you to quickly diagnose the problem.

**Comment by angelofan** [comment]
Thankfully! My test library works fine, I screened my code and found it in ionic (maybe also in xcode), causing the culprit to always return false!

Not long ago, iOS 13 was updated. In order to solve the situation that the status bar returns to white text with white background in dark mode, I added this code to the ionic config.xml file.

[Reference here](https://github.com/apache/cordova-plugin-statusbar/issues/148)

```
<config-file parent="UIUserInterfaceStyle" platform="ios" target="*-Info.plist">
  <string>Light</string>
</config-file>
```

This will cause this project to always have the bright mode theme enabled, so whether it is through js media queries or by using this plugin, it will always return false.

In order for this plugin or media query to return to the theme mode of the device, the above code must be removed from the config.xml file, not just this. When ionic compiles the iOS project, this deleted setting will not be removed from info.plist, so you need to manually remove this setting in xcode.

![image](https://user-images.githubusercontent.com/20255750/70205081-d586cc80-175d-11ea-9e46-ce21d374b998.png)

And I have confirmed that it works even when the version of cordova-ios is 4.5.5

## There are two ways to query the local dark mode

By window.matchMedia -> matchMedia
```
let mediaQueryList = window.matchMedia('(prefers-color-scheme: dark)');
console.log('Is matchMedia Available? ->',!!mediaQueryList);

let isDarkMode = mediaQueryList && mediaQueryList.matches;
console.log('Is it dark mode? ->',isDarkMode);
```

By cordova-plugin-theme-detection -> cordovaPlugin
```
cordova.plugins.ThemeDetection.isAvailable((res)=>{
  console.log('Is Theme Detection Available? ->',res);
},(err)=>{
  console.log('Error when running isAvailable ->',err);
});

cordova.plugins.ThemeDetection.isDarkModeEnabled((res)=>{
  console.log('Is it dark mode? ->',res);
},(err)=>{
  console.log('Error when running isDarkModeEnabled  ->',err);
});
```
---
In any case, there are multiple alternative codes to better maintain our project, it is worth celebrate!

**Comment by martinlyder** [comment]
I have added this lines as well. I now removed them also from the info.plist and omg it Works!!! :D Thanks @angelofan :)

**Comment by mariusbackes** [comment]
I have never seen this property in config.xml:

```
<config-file parent="UIUserInterfaceStyle" platform="ios" target="*-Info.plist">
  <string>Light</string>
</config-file>
```

But I will update my readme with common issues and write a workaround about this issue and how to fix the problem. Thank you very much @angelofan!

**Comment by StefanRein** [comment]
@angelofan Thank very very much. This was also the issue in our code base. The Media query in JS also returns always then Light.

**Comment by angelofan** [comment]
@StefanRein remove these code in `config.xml`
```
<config-file parent="UIUserInterfaceStyle" platform="ios" target="*-Info.plist">
  <string>Light</string>
</config-file>
```

then run `cordova prepare ios`

When cordova compiles the iOS project, the options deleted from config.xml will not be deleted in info.plist, it only checks for new items, so you need to manually delete this setting in xcode.
![image](https://user-images.githubusercontent.com/20255750/88399525-96df7880-cdf9-11ea-90d7-3b941f9bf56e.png)

If it still does not work, please try `cordova platform rm ios` and execute `cordova platform add ios` again.

**Comment by StefanRein** [comment]
@angelofan Hey, thanks for your reply, but it did work without having me removing it manually from the plist file.

`ionic cordova build ios --no-build --prod` because the artifact itself did not change.

Just realized these settings are coupled when I saw your post, so you saved me a bunch of time! Thanks 👍
